name: Test MY-AI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate dataset
        run: |
          python training/validate_dataset.py

      - name: Train model
        run: |
          python training/train.py

      - name: Test inference
        run: |
          printf "ඔයා කවුද?\nexit\n" | python inference/inference.py

      - name: Upload model
        uses: actions/upload-artifact@v4
        with:
          name: my-ai-model
          path: |
            my_ai.pt
            data/vocab.json
